import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { NormalizedCollection } from '../directus/normalize.js';
import { formatTypeScript } from './format.js';

/**
 * Generates the TypeScript interface for a collection
 */
function generateCollectionType(collection: NormalizedCollection): string {
  const fields = collection.fields
    .map((field) => {
      const key = field.needsQuotes ? `"${field.name}"` : field.name;
      const optional = field.optional ? '?' : '';
      return `  ${key}${optional}: ${field.type};`;
    })
    .join('\n');

  // Check if any field uses GeoJSON type
  const usesGeoJSON = collection.fields.some((field) =>
    field.type.includes('GeoJSON'),
  );
  const geoJSONImport = usesGeoJSON
    ? `import type { GeoJSON } from '../../client/types.js';\n\n`
    : '';

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from Directus collection: ${collection.name}
 */

${geoJSONImport}export interface ${collection.typeName} {
${fields}
}
`;
}

/**
 * Generates the query helper functions for a collection
 */
function generateCollectionHelpers(collection: NormalizedCollection): string {
  const baseName = collection.typeName.replace('Item_', '');

  // Use "getMany" prefix for plural and "getOne" prefix for singular
  // This avoids naming collisions completely (e.g., site vs sites)
  const functionNamePlural = `getMany${baseName}`;
  const functionName = `getOne${baseName}`;

  return `
import { getItem } from '../../runtime/getItem.js';
import { getItems } from '../../runtime/getItems.js';
import type { Query } from '../../runtime/query.js';

/**
 * Fetches multiple items from the ${collection.name} collection
 */
export async function ${functionNamePlural}(
  baseUrl: string,
  token: string,
  query?: Query<${collection.typeName}>,
): Promise<${collection.typeName}[]> {
  return getItems<${collection.typeName}>(baseUrl, '${collection.name}', token, query);
}

/**
 * Fetches a single item from the ${collection.name} collection
 */
export async function ${functionName}(
  baseUrl: string,
  token: string,
  id: string | number,
  query?: Query<${collection.typeName}>,
): Promise<${collection.typeName}> {
  return getItem<${collection.typeName}>(baseUrl, '${collection.name}', token, id, query);
}
`;
}

/**
 * Writes a collection file
 */
export async function emitCollectionFile(
  outputDir: string,
  collection: NormalizedCollection,
): Promise<void> {
  const collectionsDir = join(outputDir, 'collections');
  await mkdir(collectionsDir, { recursive: true });

  const typeCode = generateCollectionType(collection);
  const helpersCode = generateCollectionHelpers(collection);
  const fullCode = formatTypeScript(typeCode + helpersCode);

  const filePath = join(collectionsDir, `${collection.fileName}.ts`);
  await writeFile(filePath, fullCode, 'utf-8');
}

/**
 * Generates the main index file that exports all collections
 */
export async function emitIndexFile(
  outputDir: string,
  collections: NormalizedCollection[],
): Promise<void> {
  const imports = collections
    .map((col) => {
      const baseName = col.typeName.replace('Item_', '');
      const functionNamePlural = `getMany${baseName}`;
      const functionName = `getOne${baseName}`;
      return `export { ${functionNamePlural}, ${functionName} } from './collections/${col.fileName}.js';`;
    })
    .join('\n');

  const typeExports = collections
    .map(
      (col) =>
        `export type { ${col.typeName} } from './collections/${col.fileName}.js';`,
    )
    .join('\n');

  const code = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by the schema generator script.
 * Run \`pnpm generate\` to regenerate.
 */

// Collection types
${typeExports}

// Collection query helpers
${imports}
`;

  const filePath = join(outputDir, 'index.ts');
  await writeFile(filePath, formatTypeScript(code), 'utf-8');
}

/**
 * Generates the schema metadata file
 */
export async function emitSchemaFile(
  outputDir: string,
  collections: NormalizedCollection[],
): Promise<void> {
  const metadata = collections.map((col) => ({
    name: col.name,
    primaryKey: col.primaryKey,
    fields: col.fields.map((f) => f.name),
  }));

  const code = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by the schema generator script.
 * Run \`pnpm generate\` to regenerate.
 */

/**
 * Metadata about a collection
 */
export interface CollectionMetadata {
  name: string;
  primaryKey: string;
  fields: string[];
}

/**
 * Schema metadata for all collections
 */
export const SCHEMA_METADATA: CollectionMetadata[] = ${JSON.stringify(metadata, null, 2)};
`;

  const filePath = join(outputDir, 'schema.ts');
  await writeFile(filePath, formatTypeScript(code), 'utf-8');
}
